const examples={html:`<!doctype html>\n<html>\n  <head>\n    <title>MinifyCode</title>\n  </head>\n  <body>\n    <main class="hero">\n      <h1>Hello, smaller web.</h1>\n      <p>Ship less, keep the meaning.</p>\n    </main>\n  </body>\n</html>`,css:`.hero {\n  display: grid;\n  gap: 1rem;\n  color: #18221f;\n  padding: 2rem;\n}\n\n.hero h1 { margin: 0; }`,js:`// A tiny, safe example\nconst greet = (name) => {\n  const message = "Hello, " + name + "!";\n  console.log(message);\n};\n\ngreet("world");`};

const minifyCSS=source=>{const strings=[];const protectedSource=source.replace(/(["'])(?:\\.|(?!\1)[\s\S])*\1/g,value=>{strings.push(value);return`___MINIFYCODE_STRING_${strings.length-1}___`});const compacted=protectedSource.replace(/\/\*[\s\S]*?\*\//g,"").replace(/\s+/g," ").replace(/\s*([{}:;,>+~])\s*/g,"$1").replace(/;}/g,"}").trim();return compacted.replace(/___MINIFYCODE_STRING_(\d+)___/g,(_,index)=>strings[Number(index)])};

const mangleLocals=source=>{const names=new Set,usedNames=new Set(source.match(/[A-Za-z_$][\w$]*/g)||[]),keywords=new Set("arguments await break case catch class const continue debugger default delete do else export extends finally for function if import in instanceof let new return static super switch this throw try typeof var void while with yield true false null undefined console window document Math JSON Array Object String Number Boolean Promise Date RegExp Error".split(" "));const depthAt=position=>{let depth=0,quote="";for(let index=0;index<position;index++){const character=source[index];if(quote){if(character==="\\")index++;else if(character===quote)quote=""}else if(character==="'"||character==='"'||character==="`")quote=character;else if(character==="{")depth++;else if(character==="}")depth--}return depth};let match;const declarations=/\b(?:const|let|var)\s+([A-Za-z_$][\w$]*)/g;while((match=declarations.exec(source)))if(depthAt(match.index)>0&&!keywords.has(match[1]))names.add(match[1]);const namedDeclarations=/\b(?:async\s+)?function\s+([A-Za-z_$][\w$]*)\vert{}\bclass\s+([A-Za-z_$][\w$]*)/g;while((match=namedDeclarations.exec(source))){const name=match[1]\vert{}\vert{}match[2];if(name&&!keywords.has(name))names.add(name)}const functionParameters=/\b(?:async\s+)?function\s*[\w$]*\s*\(([^)]*)\)/g;while((match=functionParameters.exec(source)))match[1].split(",").map(item=>item.trim().replace(/[={}].*$/,"")).filter(item=>/^[A-Za-z_$][\w$]*$/.test(item)&&!keywords.has(item)).forEach(item=>names.add(item));

  // Исправлено: теперь стрелочные функции ищутся строго в скобках, чтобы не захватывать логические выражения со сравнениями
  const parameters=/\(([^)]*)\)\s*=>/g;
  while((match=parameters.exec(source))){const list=match[1]||"";list.split(",").map(item=>item.trim().replace(/[={}].*$/,"")).filter(item=>/^[A-Za-z_$][\w$]*$/.test(item)&&!keywords.has(item)).forEach(item=>names.add(item))}

  const replacements=new Map;let candidate=0;for(const name of names){let shortName;do{shortName=String.fromCharCode(97+(candidate++%26))+(candidate>26?Math.floor(candidate/26):"")}while(keywords.has(shortName)||usedNames.has(shortName));replacements.set(name,shortName);usedNames.add(shortName)}let cursor=0,quote="";return source.replace(/([A-Za-z_$][\w$]*)/g,(token,_match,offset)=>{for(let index=cursor;index<offset;index++){if(quote){if(source[index]==="\\")index++;else if(source[index]===quote)quote=""}else if(source[index]==="'"||source[index]==='"'||source[index]==="`")quote=source[index]}cursor=offset+token.length;if(quote)return token;const before=source.slice(0,offset).trimEnd(),after=source.slice(offset+token.length).trimStart();return before.endsWith(".")||after.startsWith(":")||keywords.has(token)?token:replacements.get(token)||token})};

const minifyJS=source=>{let result="",index=0,quote="",pendingSpace=false;const isWord=value=>/[\w$]/.test(value);const previousSignificant=()=>result[result.length-1]||"";while(index<source.length){const character=source[index],next=source[index+1]||"";if(quote){result+=character;if(character==="\\")result+=next,index++;else if(character===quote)quote="";index++;continue}if(character==="'"||character==='"'||character==="`"){if(pendingSpace&&isWord(previousSignificant())&&isWord(character))result+=" ";pendingSpace=false;quote=character;result+=character;index++;continue}if(character==="/"&&next==="/"){while(index<source.length&&source[index]!=="\n")index++;pendingSpace=true;continue}if(character==="/"&&next==="*"){index+=2;while(index<source.length&&!(source[index]==="*"&&source[index+1]==="/"))index++;index+=2;pendingSpace=true;continue}if(/\s/.test(character)){pendingSpace=true;index++;continue}if(pendingSpace&&isWord(previousSignificant())&&isWord(character))result+=" ";pendingSpace=false;result+=character;index++}return mangleLocals(result.trim())};

const minifyHTML=source=>{const protectedBlocks=[];const protectedSource=source.replace(/<(pre|textarea|script|style)\b[^>]*>[\s\S]*?<\/\1>/gi,block=>{protectedBlocks.push(block);return`___MINIFYCODE_BLOCK_${protectedBlocks.length-1}___`});let result=protectedSource.replace(/<!--[\s\S]*?-->/g,"");result=result.replace(/>\s+</g,"><").replace(/\s+/g," ").replace(/\s*(___MINIFYCODE_BLOCK_\d+___)\s*/g,"$1");result=result.replace(/\s*(=|>)\s*/g,"$1").trim();return result.replace(/___MINIFYCODE_BLOCK_(\d+)___/g,(_,number)=>{const block=protectedBlocks[Number(number)];return block.replace(/^(<script|<style)([^>]*)>/i,(_,tag,attributes)=>`${tag}${attributes.trim()>}`).replace(/(<script[^>]*>)([\s\S]*?)(<\/script>)/i,(_,open,content,close)=>`${open}${minifyJS(content)}${close}`).replace(/(<style[^>]*>)([\s\S]*?)(<\/style>)/i,(_,open,content,close)=>`${open}${minifyCSS(content)}${close}`)})};

const minifiers={html:minifyHTML,css:minifyCSS,js:minifyJS};const sourceCode=document.querySelector("#source-code"),outputCode=document.querySelector("#minified-code"),modeButtons=[...document.querySelectorAll(".mode-button")];let mode="html",lastResult="";

const updateStats=(input,output="")=>{const lines=input?input.split(/\r?\n/).length:0;document.querySelector("#input-meta").textContent=`${lines} строк · ${input.length.toLocaleString("ru-RU")} символов`;document.querySelector("#output-meta").textContent=`${output.length.toLocaleString("ru-RU")} символов`;const saved=input.length?Math.max(0,Math.round((1-output.length/input.length)*100)):0;document.querySelector("#saved-percent").textContent=output?`${saved}%`:"—";document.querySelector("#saved-chars").textContent=output?`${Math.max(0,input.length-output.length).toLocaleString("ru-RU")} знаков`:"—"};

const setMode=nextMode=>{mode=nextMode;modeButtons.forEach(button=>{const active=button.dataset.mode===mode;button.classList.toggle("is-active",active);button.setAttribute("aria-selected",String(active))});document.querySelector("#input-language").textContent=mode.toUpperCase();sourceCode.placeholder=`Вставьте ${mode.toUpperCase()}-код сюда...`;if(!sourceCode.value){outputCode.value="";document.querySelector("#output-empty").classList.remove("is-hidden")}};

const runMinify=()=>{const result=minifiers[mode](sourceCode.value);lastResult=result;outputCode.value=result;document.querySelector("#output-empty").classList.toggle("is-hidden",Boolean(result));document.querySelector("#copy-button").disabled=!result;document.querySelector("#download-button").disabled=!result;updateStats(sourceCode.value,result)};

modeButtons.forEach(button=>button.addEventListener("click",()=>setMode(button.dataset.mode)));sourceCode.addEventListener("input",()=>{document.querySelector("#drop-hint").classList.toggle("is-hidden",Boolean(sourceCode.value));updateStats(sourceCode.value)});document.querySelector("#minify-button").addEventListener("click",runMinify);document.querySelector("#clear-button").addEventListener("click",()=>{sourceCode.value="";outputCode.value="";lastResult="";document.querySelector("#drop-hint").classList.remove("is-hidden");document.querySelector("#output-empty").classList.remove("is-hidden");document.querySelector("#copy-button").disabled=true;document.querySelector("#download-button").disabled=true;updateStats("")});document.querySelector("#sample-button").addEventListener("click",()=>{sourceCode.value=examples[mode];sourceCode.dispatchEvent(new Event("input"));runMinify()});document.querySelector("#copy-button").addEventListener("click",async()=>{await navigator.clipboard.writeText(lastResult);const button=document.querySelector("#copy-button");button.innerHTML="Скопировано <span>✓</span>";window.setTimeout(()=>{button.innerHTML="Скопировать <span>↗</span>"},1400)});document.querySelector("#download-button").addEventListener("click",()=>{const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([lastResult],{type:"text/plain"}));link.download=`minified.${mode==="js"?"js":mode}`;link.click();URL.revokeObjectURL(link.href)});sourceCode.addEventListener("dragover",event=>event.preventDefault());sourceCode.addEventListener("drop",event=>{event.preventDefault();const file=event.dataTransfer?.files[0];if(!file)return;const extension=file.name.split(".").pop()?.toLowerCase();if(extension==="css"||extension==="js"||extension==="html")setMode(extension==="html"?"html":extension);const reader=new FileReader;reader.onload=()=>{sourceCode.value=String(reader.result);sourceCode.dispatchEvent(new Event("input"));runMinify()};reader.readAsText(file)});document.addEventListener("keydown",event=>{if((event.metaKey||event.ctrlKey)&&event.key==="Enter"){event.preventDefault();runMinify()}});updateStats("");
